# Generated by Django 5.2.7 on 2025-12-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
