# Generated by Django 6.0 on 2025-12-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='complexity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
