# Generated by Django 6.0 on 2025-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_userresult_user_attempt_userresult_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
